### ISSUE TITLE
WBAT has incorrect holders or circulating supply

### ISSUE THREAD

**Issue by Keith-CY** [nervosnet/godwoken_explorer#352]
![image](https://user-images.githubusercontent.com/7271329/162578976-1099d9ac-8c3f-4a7e-a8d9-91fb8a5e9018.png)

WBAT's circulating supply is 468.2 but only 1 holder holds 234.1

**Comment by zmcNotafraid** [comment]
Data has fixed.Because now supply was incremental updating, so maybe have some boundary, need more attention to it.
