### ISSUE TITLE
[Bridged Token] **WBTC|eth**

### ISSUE THREAD

**Issue by Keith-CY** [nervosnet/godwoken_explorer#353]
### Token Name

Wrapped WBTC (ForceBridge from Ethereum)

### Description

WBTC bridged from ethereum

### Symbol

WBTC|eth

### Decimals

8

### Website

https://wbtc.network/

### Logo URI

https://cryptologos.cc/logos/wrapped-bitcoin-wbtc-logo.svg

### SUDT Script Arguments

0x0a2117bce7a84cac80e7c5971919d12987e4da58f79e010c6c2f58c7d6e687e1

### Contract Address

0x79BAa5bed6E3A5BFedeED54D7dA9fEb71C7e148e

**Comment by zmcNotafraid** [comment]
Created At: https://gwscan.com/zh-CN/token/49361
