### ISSUE TITLE
The number of tokens in the first place is 0

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnet/godwoken_explorer#360]
https://gwscan.com/tokens/bridge?type=bridge&page=5
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/32102187/163139416-c76ca62e-872c-4d03-b206-4420f83a20d9.png">
#### expected
The number of tokens in the first place is not 0

**Comment by Keith-CY** [comment]
It was formatted incorrectly, the orignial value is `0.418814977251840718` while formatted value is `0,418,814,977,251,840,718`. The point was lost.

**Comment by Keith-CY** [comment]
Should be fixed in https://github.com/nervosnet/godwoken-explorer-ui/pull/132
