### ISSUE TITLE
[v1] Gasfee precision display exception

### ISSUE THREAD

**Issue by Dawn-githap** [nervosnet/godwoken_explorer#361]
> Godtoken precision is 8, and an error is displayed here

![image](https://user-images.githubusercontent.com/77844990/163140565-5af3d37c-73e7-45ab-b5b3-0e4993eeb37c.png)

**Comment by Keith-CY** [comment]
Could you append the tx in the issue so that we can find out the original data?

**Comment by Dawn-githap** [comment]
> tx: 0x51a9f5ac0bfdfa77afab74c75304f8898f35ccd17c2146f9927c8bfd2b75b5ee

**Comment by zmcNotafraid** [comment]
Gas price no need to parse again.It's already parsed from api @Keith-CY
