### ISSUE TITLE
Summary of feedbacks from Acceptance Team

### ISSUE THREAD

**Issue by Keith-CY** [nervosnet/godwoken_explorer#378]
- [Thu, Apr 14, 2022](https://workflowy.com/s/gwscan/H1snfYXWVfYcifC0)

**Comment by doitian** [comment]
[Thu, Apr 14, 2022](https://workflowy.com/s/thu-apr-14-2022/m5KanvsDYiJeqLTd)

**Comment by doitian** [comment]
Thu, Apr 14, 2022 测试碰到的问题

- 需要跨链文档和账号，实现在测试网跨链操作 gp #need-help 
  - 要测试layer1层转到2层, 桥接代币数量是否会增加
  - 想了解如何新增一个桥接代币的流程
  - 跨链今天会在 v0 上尝试
- 需要了解token Circulating Supply 的计算规则 gp #need-help 
  - 因为桥接代币没有验证合约abi,无法验证Circulating Supply是否准确活动
  - 已经提了 #375 
- 需要开发帮忙注册一个我们有代币的erc20合约，只有注册的合约才能展示在scan上面 gp #need-help 
  - 虽然erc20的标准是
    - event Transfer(address indexed _from, address indexed _to, uint256 _value)
  - 但还是有些项目方没有仔细按照标准实现erc20代币，需要验证4个合约,看能否都正确识别出是erc20代币
    - event Transfer(address indexed _from, address indexed _to, uint256 _value)
    - event Transfer(address indexed _from, address indexed _to, uint256 indexed _value)
    - event Transfer(address indexed _from, address _to, uint256 _value)
    - event Transfer(address _from, address _to, uint256 _value)
  - xiefei 的问题也是需要一个erc20合约记录 现在还没构造出来
  - 跨链今天会在 v0 上尝试
- 需要直接从godwoken链获取gwscan图表所展示的的原始数据的途径和方法 李涵 #done
  - gwscan图表所展示的数据（包括平均区块大小、平均出块时间、出块总数、交易总数、平均Gas消耗/上限、ERC20代币转账次数）是gwscan积累数据生成的，但在测试时从godwoken 链直接获取数据作为校验，但gw目前并没有提供获取相关数据的rpc方法。目前gwscan开发人员给出的建议是寻找以太坊看是否有现成的可用的脚本，但具体如何操作还不清楚。
  - 李涵反馈：已经解决，通过gw rpc方法可以间接得到数据

**Comment by doitian** [comment]
Feel free to close this issue. I'll aggregate questions in new issues, such as #383
