### ISSUE TITLE
[Question] Cryptape Testing Team Questions 2022-04-15

### ISSUE THREAD

**Issue by doitian** [nervosnet/godwoken_explorer#383]
- [x] 1. How the token holders txns is computed?

    ![image](https://user-images.githubusercontent.com/35768/163524956-7cb41a39-54fc-42be-8956-ad8bd2fd12cc.png)

**Comment by zmcNotafraid** [comment]
> 1. How the token holders txns is computed?
>    ![image](https://user-images.githubusercontent.com/35768/163524956-7cb41a39-54fc-42be-8956-ad8bd2fd12cc.png)

If account is  a user type, transaction count is user's nonce and add 1.
Other type account, query from transactions table that to account equal this account,get the sum.
