### ISSUE TITLE
[v1] Polyjuice Account 's  Transaction Count is 0

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnet/godwoken_explorer#385]
url:https://v1.aggron.gwscan.com/account/0x5d0666bae2a0116ffb37e2d5684a3b432c3b7e73
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/32102187/163531461-27c0256d-6ef5-4e48-b5b5-6dfc52e17dbb.png">

**Comment by zmcNotafraid** [comment]
```
curl https://godwoken-testnet-web3-v1-rpc.ckbapp.dev -X POST -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"gw_get_nonce","params": ["0x6"],"id":1}'       
{"jsonrpc":"2.0","id":1,"result":"0x0"}%
```
I query from rpc the nonce is 0, so what happened? @gpBlockchain

**Comment by gpBlockchain** [comment]
check v0 `Polyjuice Account` transaction count
https://www.gwscan.com/account/0x8adcb6adf12a1dc8d3302c5129c5feb12cbec229?search=0x8adcb6adf12a1dc8d3302c5129c5feb12cbec229&id=0x8adcb6adf12a1dc8d3302c5129c5feb12cbec229&page=2

**Comment by zmcNotafraid** [comment]
Fixed. This account is polyjuice creator type.
