### ISSUE TITLE
[Question] Cryptape Testing Team Questions 2022-04-18

### ISSUE THREAD

**Issue by doitian** [nervosnet/godwoken_explorer#389]
- [ ] 1. What does the transaction status "Pending" mean? How to verify that a transaction is pending?

![image](https://user-images.githubusercontent.com/35768/163744859-c96d33b2-9082-494e-8a20-dca48aed42af.png)

**Comment by gpBlockchain** [comment]
Why is this transaction in a pending state
https://www.gwscan.com/tx/0x2f20d3f1477a4cdde48301556c7114fc6e54f41bce2e839448b41ffc1d58b1d1

**Comment by zmcNotafraid** [comment]
Status here we only use for polyjuice type transaction.But here is a  polyjuice creator  type transaction. So it will return nil for status.We will enhance it to return a normal value.

**Comment by Keith-CY** [comment]
Will be closed once the PR is merged
